# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
- develop

pool:
  name: 'Default'

stages:
  - stage: buildAndAnalyse
    displayName: 'Maven Build and Sonarqube Analysis'
    jobs: 
      - job: 'Build'
        displayName: 'Build'
        steps:
          - task: 'SonarQubePrepare@5'
            displayName: 'Sonarqube Prepare'
            inputs:
              SonarQube: 'sonar'
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: 'githubconnec_githubconnec_472edd1d-6d19-47d2-9893-e7092aaf8408'
              cliProjectName: 'githubconnec'
              cliSources: '.'
              
          - task: 'JavaToolInstaller@0'
            displayName: 'Java Tool Install'
            inputs:
              versionSpec: '17'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled' 
              
          - task: Maven@4
            displayName: 'Maven Build'
            inputs:
                  mavenPomFile: 'pom.xml'
                  goals: 'install'
                  publishJUnitResults: true
                  testResultsFiles: '**/surefire-reports/TEST-*.xml'
                 
          - task: 'SonarQubeAnalyze@5'
        

          - task: SonarQubePublish@5
            displayName: 'sonarqube publish'
            inputs:
              pollingTimeoutSec: '300'
