# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: 'Default'

stages:
  - stage: buildAndAnalyse
    displayName: 'Maven Build and Sonarqube Analysis'
    jobs: 
      - job: 'Build'
        displayName: 'Build'
        steps:
          - task: 'SonarQubePrepare@5'
            displayName: 'Sonarqube Prepare'
            inputs:
              SonarQube: 'sonarqube'
              scannerMode: 'Other'
              extraProperties: |
                sonar.projectKey=githubconnec_githubconnec_472edd1d-6d19-47d2-9893-e7092aaf8408
                sonar.projectName=githinconnec
              
          - task: Maven@4
            displayName: 'Maven Build'
            inputs:
                  mavenPomFile: 'pom.xml'
                  goals: 'install sonar:sonar'
                  publishJUnitResults: true
                  testResultsFiles: '**/surefire-reports/TEST-*.xml'
                  mavenVersionOption: 'Default'
                  javaHomeOption: 'JDKVersion'
                  mavenAuthenticateFeed: false
                  effectivePomSkip: false
                  sonarQubeRunAnalysis: true
                  sqMavenPluginVersionChoice: 'latest'

        

          - task: SonarQubePublish@5
            displayName: 'sonarqube publish'
            inputs:
              pollingTimeoutSec: '300'
