---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: kiran
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: kiran023/backend
        name: backend
        ports:
        - containerPort: 8086
        resources: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  
  labels:
    app: frontend
  name: frontend
  namespace: kiran
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      
      labels:
        app: frontend
    spec:
      containers:
      - image: kiran023/frontend
        name: frontend
        ports:
        - containerPort: 8085
        resources: {}
        env:
           - name: BACKEND
             value: "http://backend:8086"
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
  namespace: kiran
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8086-8086
    port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: backend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:  
  labels:
    app: frontend
  name: frontend
  namespace: kiran 
spec: 
  ports:
  - name: 8085-8085
    port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: frontend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}

